include theos/makefiles/common.mk

APPLICATION_NAME = safemodeicon
safemodeicon_FILES = main.m safemodeiconApplication.mm RootViewController.mm
safemodeicon_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
